#  خلاصه نویسی نیمایی (جبرخطی در پایتون) :D

# Nima81ghasemi@proton.me

#  V1.00

In [63]:
"""
1) بردارها و محاسبات برداری
2) نرم برداری
3) ماتریس ها و محاسبات ماتریسی
4) انواع ماتریس
5) etc
"""

'\n1) بردارها و محاسبات برداری\n2) نرم برداری\n3) ماتریس ها و محاسبات ماتریسی\n4) انواع ماتریس\n5) etc\n'

# بردارها و محاسبات برداری

In [64]:
# ساخت یک بردار
from numpy import array
v = array([1, 2, 3])
print(v)

[1 2 3]


In [65]:
type(v)

numpy.ndarray

In [66]:
# جمع برداری
"""
a and b are array(vector)
c = a + b
c = (a1 + b1, a2 + b2, a3 + b3)
"""

'\na and b are array(vector)\nc = a + b\nc = (a1 + b1, a2 + b2, a3 + b3)\n'

In [67]:
from numpy import array
a = array([1, 2, 3])
print(a)

b = array([1, 2, 3])
print(b)

c = a + b
print(c)

[1 2 3]
[1 2 3]
[2 4 6]


In [68]:
# تفریق برداری
"""
a and b are array(vector)
c = a - b
c = (a1 - b1, a2 - b2, a3 - b3)
"""

'\na and b are array(vector)\nc = a - b\nc = (a1 - b1, a2 - b2, a3 - b3)\n'

In [69]:
from numpy import array
a = array([1, 2, 3])
print(a)

b = array([1, 2, 3])
print(b)

c = a - b
print(c)

[1 2 3]
[1 2 3]
[0 0 0]


In [70]:
# ضرب برداری
"""
a and b are array(vector)
c = a * b
c = (a1 * b1, a2 * b2, a3 * b3)
"""

'\na and b are array(vector)\nc = a * b\nc = (a1 * b1, a2 * b2, a3 * b3)\n'

In [71]:
from numpy import array
a = array([1, 2, 3])
print(a)

b = array([1, 2, 3])
print(b)

c = a * b
print(c)

[1 2 3]
[1 2 3]
[1 4 9]


In [72]:
# تقسیم برداری
"""
a and b are array(vector)
c = a / b
c = (a1 / b1, a2 / b2, a3 / b3)
"""

'\na and b are array(vector)\nc = a / b\nc = (a1 / b1, a2 / b2, a3 / b3)\n'

In [73]:
from numpy import array
a = array([1, 2, 3])
print(a)

b = array([1, 2, 3])
print(b)

c = a / b
print(c)

[1 2 3]
[1 2 3]
[1. 1. 1.]


In [74]:
# ضرب داخلی
"""
a and b are array(vector)
c = a . b
c = ((a1 * b1) + (a2 * b2) + (a3 * b3))
"""

'\na and b are array(vector)\nc = a . b\nc = ((a1 * b1) + (a2 * b2) + (a3 * b3))\n'

In [75]:
from numpy import array
a = array([1, 2, 3])
print(a)

b = array([1, 2, 3])
print(b)

c = a.dot(b)
print(c)

[1 2 3]
[1 2 3]
14


In [76]:
# ضرب بردار اسکالر
"""
v is an array(vector)
n is a number
c = n * v
c = (n * v1, n * v2, n * v3)
"""

'\nv is an array(vector)\nn is a number\nc = n * v\nc = (n * v1, n * v2, n * v3)\n'

In [77]:
from numpy import array
v = array([1, 2, 3])
print(v)

n = 5
print(n)

c = n * v
print(c)

[1 2 3]
5
[ 5 10 15]


# نرم های برداری

#### علامت نرم در ریاضی است ||x||

#### نرم برداری = محاسبه طول یا اندازه بردار

In [78]:
# l1
"""
l1(v) = (((v1**2)**0.5) + ((v2**2)**0.5) + ((v3**2)**0.5))
"""

'\nl1(v) = (((v1**2)**0.5) + ((v2**2)**0.5) + ((v3**2)**0.5))\n'

In [79]:
from numpy import array
from numpy.linalg import norm

a = array([1, 2, 3])
print(a)

l1 = norm(a, 1)
print(l1)

[1 2 3]
6.0


In [80]:
# l2
"""
l2(v) = (((v1 ** 2) + (v1 ** 2) + (v1 ** 2)) ** 0.5)
"""

'\nl2(v) = (((v1 ** 2) + (v1 ** 2) + (v1 ** 2)) ** 0.5)\n'

In [81]:
from numpy import array
from numpy.linalg import norm

a = array([1, 2, 3])
print(a)

l2 = norm(a)
print(l2)

[1 2 3]
3.7416573867739413


In [82]:
# linf
"""
linf(v) = max v1 v2 v3 
"""

'\nlinf(v) = max v1 v2 v3 \n'

In [83]:
from math import inf
from numpy import array
from numpy.linalg import norm

a = array([1, 2, 3])
print(a)

linf = norm(a, inf)
print(linf)

[1 2 3]
3.0


# ماتریس ها و محاسبات ماتریسی

In [84]:
# ساخت ماتریس

In [85]:
from numpy import array

A = array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [86]:
# A + B

In [87]:
from numpy import array

A = array([[1, 2, 3], [4, 5, 6]])
print('A : \n', A, '\n')

B = array([[1, 2, 3], [4, 5, 6]])
print('B : \n', B, '\n')

C = A + B
print('A + B : \n', C)

A : 
 [[1 2 3]
 [4 5 6]] 

B : 
 [[1 2 3]
 [4 5 6]] 

A + B : 
 [[ 2  4  6]
 [ 8 10 12]]


In [88]:
# A - B

In [89]:
from numpy import array

A = array([[1, 2, 3], [4, 5, 6]])
print('A : \n', A, '\n')

B = array([[1, 2, 3], [4, 5, 6]])
print('B : \n', B, '\n')

C = A - B
print('A - B : \n', C)

A : 
 [[1 2 3]
 [4 5 6]] 

B : 
 [[1 2 3]
 [4 5 6]] 

A - B : 
 [[0 0 0]
 [0 0 0]]


In [90]:
# A * B
# (از نظر ریاضی برای ماتریس ها درست نیست جوابش)

In [91]:
from numpy import array

A = array([[1, 2, 3], [4, 5, 6]])
print('A : \n', A, '\n')

B = array([[1, 2, 3], [4, 5, 6]])
print('B : \n', B, '\n')

C = A * B
print('A * B : \n', C)

A : 
 [[1 2 3]
 [4 5 6]] 

B : 
 [[1 2 3]
 [4 5 6]] 

A * B : 
 [[ 1  4  9]
 [16 25 36]]


In [92]:
# A / B
# (از نظر ریاضی برای ماتریس ها درست نیست جوابش)

In [93]:
from numpy import array

A = array([[1, 2, 3], [4, 5, 6]])
print('A : \n', A, '\n')

B = array([[1, 2, 3], [4, 5, 6]])
print('B : \n', B, '\n')

C = A / B
print('A / B : \n', C)

A : 
 [[1 2 3]
 [4 5 6]] 

B : 
 [[1 2 3]
 [4 5 6]] 

A / B : 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [94]:
# A . B

In [95]:
from numpy import array

A = array([[1, 2], [3, 4], [5, 6]])
print('A : \n', A, '\n')

B = array([[1, 2], [3, 4]])
print('B : \n', B, '\n')

C = A.dot(B)
print('A . B : \n', C)

A : 
 [[1 2]
 [3 4]
 [5 6]] 

B : 
 [[1 2]
 [3 4]] 

A . B : 
 [[ 7 10]
 [15 22]
 [23 34]]


In [96]:
# نکته های مهم
"""
ما میتونیم به جای نوشتن
A.dot(B)
بنویسیم
A @ B
همون کار رو انجام میده
------------------------
اگر یک ستون و ان تا سطر یا یک سطر و ان تا ستون داشته باشیم
بهش بردار میگن
ولی اگر بیشتر از یک ستون و سطر داشته باشثیم 
بهش میگن ماتریس
------------------------
برای ضرب دو ماتریس در هم باید تعداد ستون ماتریس اول با سطر ماتریس دوم برابر باشه
ولی تو اینجا یه مقدار جواب ها از لحاظ ریاضی متفاوت هستش
من دیگه نمینویسم از لحاظ ریاضی درست یا نادرست است
"""

'\nما میتونیم به جای نوشتن\nA.dot(B)\nبنویسیم\nA @ B\nهمون کار رو انجام میده\n------------------------\nاگر یک ستون و ان تا سطر یا یک سطر و ان تا ستون داشته باشیم\nبهش بردار میگن\nولی اگر بیشتر از یک ستون و سطر داشته باشثیم \nبهش میگن ماتریس\n------------------------\nبرای ضرب دو ماتریس در هم باید تعداد ستون ماتریس اول با سطر ماتریس دوم برابر باشه\nولی تو اینجا یه مقدار جواب ها از لحاظ ریاضی متفاوت هستش\nمن دیگه نمینویسم از لحاظ ریاضی درست یا نادرست است\n'

In [97]:
# ضرب بردار در ماتریس

In [98]:
from numpy import array

A = array([[1, 2], [3, 4], [5, 6]])
print(A, '\n')

B = array([0.5, 0.5])
print(B, '\n')

C = A @ B
print(C)

[[1 2]
 [3 4]
 [5 6]] 

[0.5 0.5] 

[1.5 3.5 5.5]


In [99]:
# ضرب ماتریس اسکالر

In [100]:
from numpy import array

A = array([[1, 2], [3, 4], [5, 6]])
print('A : \n', A, '\n')

B = 2
print('B : \n', B, '\n')

C = A * B
print('A * B : \n', C)

A : 
 [[1 2]
 [3 4]
 [5 6]] 

B : 
 2 

A * B : 
 [[ 2  4]
 [ 6  8]
 [10 12]]


# انواع ماتریس

In [101]:
# مربعی
"""
    1  2
    3  4
    
    n = m
"""

'\n    1  2\n    3  4\n    \n    n = m\n'

In [102]:
# متقارن
"""
    1  2
    2  1
    
    n = m
    M = M(T) transpose
"""

'\n    1  2\n    2  1\n    \n    n = m\n    M = M(T) transpose\n'

In [103]:
# مثلثی
"""
    1  2  3
    0  2  3
    0  0  3
    مثلثی بالا هستش
    ----------------
    1  0  0
    1  2  0
    1  2  3
    مثلثی پایین هستش
"""

'\n    1  2  3\n    0  2  3\n    0  0  3\n    مثلثی بالا هستش\n    ----------------\n    1  0  0\n    1  2  0\n    1  2  3\n    مثلثی پایین هستش\n'

In [104]:
# قطری
"""
    1  0  0
    0  2  0
    0  0  3
"""

'\n    1  0  0\n    0  2  0\n    0  0  3\n'

In [105]:
# همانی
"""
    1  0  0
    0  1  0
    0  0  1
"""

'\n    1  0  0\n    0  1  0\n    0  0  1\n'

In [106]:
# identity matrix
from numpy import identity
I = identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [107]:
# ماتریس متعامد
"""
M . MT = I
"""

'\nM . MT = I\n'

In [108]:
from numpy import array
from numpy.linalg import inv

M = array([[1, 0], [0, -1]])
print(M, '\n')

MT = inv(M)
print(MT, '\n')

I = M @ MT
print(I)

[[ 1  0]
 [ 0 -1]] 

[[ 1.  0.]
 [-0. -1.]] 

[[1. 0.]
 [0. 1.]]
